# Default initial positions for panda

initial_positions:
  panda_joint1: 0
  panda_joint2: 0
  panda_joint3: 0
  panda_joint4: 0
  panda_joint5: 0
  panda_joint6: 0
  panda_joint7: 0
  panda_finger_joint1: 0
  panda_finger_joint2: 0
